fix: change appID

diff --git a/.github/workflows/deplpy_github_actions_and_fire_base.yml b/.github/workflows/deplpy_github_actions_and_fire_base.yml
--- a/.github/workflows/deplpy_github_actions_and_fire_base.yml
+++ b/.github/workflows/deplpy_github_actions_and_fire_base.yml
@@ -10,7 +10,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
@@ -34,31 +33,39 @@ jobs:
           VARIANT_NAME="${PRODUCT}${SIDEPERSONA^}Release"
           ./gradlew :app:assemble${VARIANT_NAME}
 
-      - name: Set environment variable for FIREBASE APP_ID
+      - name: Set environment variable for APP_ID
         run: |
           PRODUCT=${{ matrix.product }}
           SIDEPERSONA=${{ matrix.sidePersona }}
-          APP_ID="FIREBASE_APP_ID_${PRODUCT^^}_${SIDEPERSONA^^}"
-          echo "FIRE BAE APP ID $APP_ID" 
+          APP_ID_KEY="FIREBASE_APP_ID_${PRODUCT^^}_${SIDEPERSONA^^}"
+          echo "APP_ID=${{ secrets[${APP_ID_KEY}] }}" >> $GITHUB_ENV
+
+      - name: Verify APP_ID
+        run: |
+          if [ -z "${{ env.APP_ID }}" ]; then
+            echo "APP_ID is not set or invalid"
+            exit 1
 
       - name: Verify APK exists
         run: |
           PRODUCT=${{ matrix.product }}
           SIDEPERSONA=${{ matrix.sidePersona }}
           VARIANT_NAME="${PRODUCT}${SIDEPERSONA^}"
-          APK_PATH="app/build/outputs/apk/${VARIANT_NAME}/release/app-${PRODUCT}-${SIDEPERSONA}-release-unsigned.apk"
+          APK_PATH="app/build/outputs/apk/${VARIANT_NAME}/release/app-${VARIANT_NAME}-release-unsigned.apk"
           echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
-          echo "PATH APK $APK_PATH"
-
           if [ ! -f $APK_PATH ]; then
             echo "APK not found at $APK_PATH"
             exit 1
-          fi
+
+      - name: Print APP_ID and APK_PATH
+        run: |
+          echo "APP_ID: ${{ env.APP_ID }}"
+          echo "APK_PATH: ${{ env.APK_PATH }}"
 
       - name: Upload artifact to Firebase App Distribution
         uses: wzieba/Firebase-Distribution-Github-Action@v1
         with:
-          appId: ${{ secrets[env.APP_ID] }}
+          appId: ${{ env.APP_ID }}
           serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
           groups: "Teste whiteLabelApp"
           file: ${{ env.APK_PATH }}
